"""empty message

Revision ID: 919647924b0b
Revises: f2a507ac545d
Create Date: 2024-02-25 11:56:02.211392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '919647924b0b'
down_revision: Union[str, None] = 'f2a507ac545d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('parts', sa.Column('resistance', sa.Float(), nullable=True))
    op.add_column('parts', sa.Column('inductance', sa.Float(), nullable=True))
    op.add_column('parts', sa.Column('capacitance', sa.Float(), nullable=True))
    op.add_column('parts', sa.Column('dielectric', sa.String(), nullable=True))
    op.add_column('parts', sa.Column('current', sa.Float(), nullable=True))
    op.add_column('parts', sa.Column('voltage', sa.Float(), nullable=True))
    op.create_index(op.f('ix_parts_capacitance'), 'parts', ['capacitance'], unique=False)
    op.create_index(op.f('ix_parts_current'), 'parts', ['current'], unique=False)
    op.create_index(op.f('ix_parts_dielectric'), 'parts', ['dielectric'], unique=False)
    op.create_index(op.f('ix_parts_inductance'), 'parts', ['inductance'], unique=False)
    op.create_index(op.f('ix_parts_resistance'), 'parts', ['resistance'], unique=False)
    op.create_index(op.f('ix_parts_voltage'), 'parts', ['voltage'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parts_voltage'), table_name='parts')
    op.drop_index(op.f('ix_parts_resistance'), table_name='parts')
    op.drop_index(op.f('ix_parts_inductance'), table_name='parts')
    op.drop_index(op.f('ix_parts_dielectric'), table_name='parts')
    op.drop_index(op.f('ix_parts_current'), table_name='parts')
    op.drop_index(op.f('ix_parts_capacitance'), table_name='parts')
    op.drop_column('parts', 'voltage')
    op.drop_column('parts', 'current')
    op.drop_column('parts', 'dielectric')
    op.drop_column('parts', 'capacitance')
    op.drop_column('parts', 'inductance')
    op.drop_column('parts', 'resistance')
    # ### end Alembic commands ###
