"""empty message

Revision ID: f2a507ac545d
Revises: 1b3360ddd371
Create Date: 2024-02-24 16:17:52.988335

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f2a507ac545d'
down_revision: Union[str, None] = '1b3360ddd371'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_parts_lcsc'), 'parts', ['lcsc'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_parts_lcsc'), table_name='parts')
    # ### end Alembic commands ###
